name: Build and Deploy React App

on:
  push:
    branches: [main, master] # or your default branch
    paths:
      - "client/**" # Only trigger when files in client directory change
  issues:
    types:
      - opened
env:
  REACT_APP_API_URL: "https://file-sharing-pu9d.onrender.com/api"
  CI: ""

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # or your preferred version
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Set environment variables from secrets
        run: |
          echo "REACT_APP_STRIPE_PUBLIC_KEY=${{ secrets.REACT_APP_API_URL }}" >> $GITHUB_ENV

      - name: Build React app
        run: |
          cd client
          npm run build
        env:
          REACT_APP_API_URL: ${{ env.REACT_APP_API_URL }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
          keep_files: true # keeps existing files in gh-pages branch
